import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv

load_dotenv()

def send_newsletter(content_html, subject="[주간 리포트] 난임 치료 및 배아 연구 동향"):
    """
    구성된 HTML 뉴스레터를 이메일로 발송합니다.
    """
    smtp_server = os.getenv("EMAIL_SMTP_SERVER")
    smtp_port = int(os.getenv("EMAIL_SMTP_PORT", 587))
    smtp_user = os.getenv("EMAIL_USER")
    smtp_password = os.getenv("EMAIL_PASSWORD")
    recipient_emails = os.getenv("RECIPIENT_EMAILS", "").split(",")

    if not all([smtp_server, smtp_user, smtp_password, recipient_emails]):
        print("이메일 설정이 누락되었습니다. (.env 파일을 확인하세요)")
        return False

    try:
        msg = MIMEMultipart()
        msg['From'] = smtp_user
        msg['To'] = ", ".join(recipient_emails)
        msg['Subject'] = subject

        msg.attach(MIMEText(content_html, 'html'))

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
            
        print(f"이메일 발송 성공: {len(recipient_emails)}명에게 전달되었습니다.")
        return True
    except Exception as e:
        print(f"이메일 발송 실패: {e}")
        return False

def format_as_html(news_summary, paper_summary):
    """
    요약된 내용을 이메일용 HTML로 변환합니다.
    """
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Malgun Gothic', sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 800px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-top: 5px solid #ff7f50; }}
            h1 {{ color: #d35400; border-bottom: 2px solid #d35400; padding-bottom: 10px; }}
            h2 {{ color: #27ae60; margin-top: 30px; }}
            .item {{ margin-bottom: 20px; padding: 15px; background: #fff5ee; border-radius: 5px; }}
            .title {{ font-weight: bold; font-size: 1.1em; color: #2e86c1; }}
            .summary {{ margin: 10px 0; }}
            .link {{ color: #7f8c8d; font-size: 0.9em; }}
            .footer {{ margin-top: 40px; font-size: 0.8em; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>주간 난임 & 배아 연구 동향 뉴스레터</h1>
            <p>본 메일은 AI(Gemini 3 Flash)를 통해 자동 생성된 생명공학 분야 핵심 브리핑입니다.</p>
            
            <h2>📰 최신 뉴스 (Latest News)</h2>
            <div class="item">
                <div class="summary">{news_summary.replace('\n', '<br>')}</div>
            </div>

            <h2>📚 주요 논문 (PubMed Research)</h2>
            <div class="item">
                <div class="summary">{paper_summary.replace('\n', '<br>')}</div>
            </div>

            <div class="footer">
                © 2026 Fertility Research Weekly | Generated by Google Gemini Flash
            </div>
        </div>
    </body>
    </html>
    """
    return html
